config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'puns#index'
  resources :puns

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pun.rb
class Pun < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/puns_controller.rb
class PunsController < ApplicationController
  def index
    @pun = Pun.order("RANDOM()").first
  end

  def new
    @pun = Pun.new
  end

  def create
    Pun.create(pun_params)
    redirect_to root_path
  end

  private

  def pun_params
    params.require(:pun).permit(:joke)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puns_helper.rb
module PunsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Popquiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
       <%= link_to 'Pun-dit', root_path, class: 'navbar-brand' %>
     </nav>
    </div>

    <br class="clear" />
      

    <%= yield %>
    
    <!-- Footer -->
<footer class="page-footer font-small blue fixed-bottom">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">Enter Your own Pun:
    <%= link_to 'Submit Here', new_pun_path, class: 'footer-copyright text-center py-3' %>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
  
  </body>
</html>

app/views/puns/index.html.erb
<h1><%= @pun.joke %></h1>


  

app/views/puns/new.html.erb
<h1>Enter your pun here</h1>
<br />
<%= simple_form_for @pun do |f| %>
  <%= f.input :joke %>
<br />
  <%= f.submit 'Submit', class: 'btn btn-secondary' %>
<% end %>